---
- name: "Filesystem"
  hosts: AIX # Vai executar apenas nos servidores do grupo AIX (definido no hosts)
  gather_facts: yes
  vars:
    log_file: "/tmp/ansible_filesystem_debug.log"

  tasks:
    - name: "Creating a Oracle VG"
      ibm.power_aix.lvg:
        state: present #Se existir utiliza o existente, se não, cria
        pvs: hdisk0 # É necessário informar o nome do hdisk
        vg_name: oracle # Informar o nome do VG
        pp_size: 1024 # Physical partition SIZE in megabytes
        vg_type: scalable

    - name: "Varyon VG"
      ibm.power_aix.lvg:
        vg_name: oracle # Nome do VG
        state: varyon

    - name: "Creation of a JFS2 filesystem"
      ibm.power_aix.filesystem:
        state: present 
        filesystem: /data # Informar o nome do Filesystem
        fs_type: jfs2 # Tipo do filesystem
        attributes: size=5G,isnapshot='no' # Informar o tamanho do Filesystem
        permissions: rw
        auto_mount: yes # Monta automaticamente
        vg: oracle # Informar o nome do VG

    - name: "Mount Filesystem"
      ibm.power_aix.mount:
        state: mount
        mount_dir: /data 
        
