---
- name: HMC Get LPAR state
  hosts: hmcs
  collections:
    - ibm.power_hmc
  connection: local
  vars:
    curr_hmc_auth:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  vars_prompt:
    - name: lpar_name # variavel que recebe o nome digitado pelo usuario
      prompt: Digite o nome da LPAR # Informar o nome do VG
      private: false

  tasks:
    - name: "Get LPAR state"
      powervm_lpar_instance:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth: "{{ curr_hmc_auth }}"
        vm_name: "{{ lpar_name }}"
        state: facts
      register: lpar_state

    - name: "Show debug"
      ansible.builtin.debug:
        var: lpar_state
