---
# Collect informations hosts
- name: Get hosts informations
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_SLES
  tasks:
    - # tasks that only happen on SUSE go here
    - name: Get disk informations
      ansible.builtin.shell: |
        fdisk -l
        lsblk
        df -h
      register: os_disk
    
    - name: Get OS Informations
      ansible.builtin.shell: |
        cat /etc/os-release
        uname -a
        cat /proc/cpuinfo
        cat /proc/meminfo | grep -i mem
      register: os_system
    
    - debug: 
        var: os_disk 

    - debug:
        var: os_system
    

- hosts: os_CentOS
  tasks:
    - # tasks that only happen on SUSE go here
    - name: Get disk informations
      ansible.builtin.shell: |
        cat /etc/os-release
        fdisk -l
        lsblk
        df -h
      register: os_disk
    
    - name: Get OS Informations
      ansible.builtin.shell: |
        cat /etc/os-release
        uname -a
        cat /proc/cpuinfo
        cat /proc/meminfo | grep -i mem
      register: os_system
    
    - debug:
        msg: "{{ os_disk.stdout_lines }}"        
    - debug:
        var: os_system

- hosts: os_AIX
  tasks:
    - # tasks that only happen on SUSE go here
    - name: Get disk informations
      ansible.builtin.shell: |
        oslevel -s
        lspv
        df -g
      register: os_disk
    
    - debug:
        msg: "{{ os_disk.stdout_lines }}"        
