---
- name: Copy files to servers
  hosts: aix # Informe o grupo de hosts que voce quer que seja executado

  vars_prompt:
    - name: filesrc # variavel para receber o nome do arquivo
      prompt: Informe o caminho completo do arquivo que ser치 copiado
      private: no
    - name: filedst # variavel para receber o diretorio de destino para onde o arquivo sera copiado
      prompt: Informe o diret칩rio de destino
      private: no

  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ filesrc }}" # Utiliza o nome do arquivo digitado pelo usu치rio
        dest: "{{ filedst }}/" # Utiliza o nome do diret칩rio para onde o arquivo deve ser copiado. Eu insiro uma barra no final para prevenir erros.
      when: ansible_distribution == "AIX" and ansible_distribution_version == "7.3"
