---
- name: "Install packages (Linux or AIX)"
  hosts: all # Especificar os servidores onde vamos executar os servidores (definido no arquivo hosts)
  gather_facts: true
  # log - /var/log/ansible.log (definido no ansible.cfg)
  vars_prompt:
    - name: applist
      prompt: "Informe o nome do software separado por virgula" # variavel que recebe o nome do software que sera instalado
      private: false

  tasks:
    - set_fact:
        applist: "{{ applist.split(',') }}"

    - name: Installing packages on AIX 7.2
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ applist }}"
      when: ansible_distribution == "AIX" and ansible_distribution_version == "7.2"

    - name: Installing packages on AIX 7.3
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ applist }}"
      environment:
        PATH: /opt/freeware/bin/
      vars:
        ansible_python_interpreter: "/opt/freeware/bin/python3"
      when: ansible_distribution == "AIX" and ansible_distribution_version == "7.3"

    - name: Installing packages on Linux CentOS
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ applist }}"
      environment:
        PATH: /opt/freeware/bin/
      vars:
        ansible_python_interpreter: "/usr/bin/python3"
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "8"

    - name: Installing packages on Linux SUSE
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ applist }}"
      environment:
        PATH: /opt/freeware/bin/
      vars:
        ansible_python_interpreter: "/usr/bin/python3.6"
      when: ansible_distribution == "SUSE" and ansible_distribution_version == "15.4"
