---
- name: "AIX - Automation and Disk operations"
  hosts: aix # Vai executar apenas nos servidores do grupo AIX (definido no hosts)
  gather_facts: no
  # log - /var/log/ansible.log (definido no ansible.cfg)
  vars_prompt:  
    - name: volumegroup # Informar o nome do VG
      prompt: Informe o nome do vg
      private: no

    - name: filesystem # Informar o nome do Filesystem
      prompt: Informe o nome do filesystem
      private: no

  tasks:
    - name: "Creating a Oracle VG"
      ibm.power_aix.lvg:
        state: present #Se existir utiliza o existente, se não, cria
        pvs: hdisk0 # É necessário informar o nome do hdisk
        vg_name: '{{ volumegroup }}' # usa o nome do VG especificado na variavel
        pp_size: 1024 # Physical partition SIZE in megabytes
        vg_type: scalable

    - name: "Varyon VG"
      ibm.power_aix.lvg:
        vg_name: '{{ volumegroup }}' # Nome do VG
        state: varyon

    - name: "Creation of a JFS2 filesystem"
      ibm.power_aix.filesystem:
        state: present
        filesystem: "/{{ filesystem }}" # Utiliza o nome do Filesystem digitado
        fs_type: jfs2 # Tipo do filesystem
        attributes: size=5G,isnapshot='no' # Informar o tamanho do Filesystem
        permissions: rw
        auto_mount: yes # Monta automaticamente
        vg: '{{ volumegroup }}' # Utiliza o nome do VG digitado

    - name: "Mount Filesystem"
      ibm.power_aix.mount:
        state: mount
        mount_dir: "/{{ filesystem }}" 
        
